<?php

// Generated by Haxe 3.4.7
class ufront_core_InjectionTools {
	public function __construct(){}
	static function listMappings($injector, $arr = null, $prefix = null) {
		$GLOBALS['%s']->push("ufront.core.InjectionTools::listMappings");
		$__hx__spos = $GLOBALS['%s']->length;
		if($prefix === null) {
			$prefix = "";
		}
		$arr1 = (new _hx_array(array()));
		ufront_core_InjectionTools::listMappingsRecursive($injector, $arr1, "");
		{
			$GLOBALS['%s']->pop();
			return $arr1;
		}
		$GLOBALS['%s']->pop();
	}
	static function listMappingsRecursive($injector, $arr, $prefix) {
		$GLOBALS['%s']->push("ufront.core.InjectionTools::listMappingsRecursive");
		$__hx__spos = $GLOBALS['%s']->length;
		if($injector->parent !== null) {
			ufront_core_InjectionTools::listMappingsRecursive($injector->parent, $arr, "(parent)" . _hx_string_or_null($prefix));
		}
		{
			$r = $injector->mappings->iterator();
			while($r->hasNext()) {
				$r1 = $r->next();
				$arr->push(_hx_string_or_null($prefix) . _hx_string_or_null($r1->toString()));
				unset($r1);
			}
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'ufront.core.InjectionTools'; }
}
