<?php

// Generated by Haxe 3.4.7
class minject_point_PropertyInjectionPoint implements minject_point_InjectionPoint{
	public function __construct($field, $type, $name = null) {
		if(!php_Boot::$skip_constructor) {
		$GLOBALS['%s']->push("minject.point.PropertyInjectionPoint::new");
		$__hx__spos = $GLOBALS['%s']->length;
		$this->field = $field;
		$this->type = $type;
		$this->name = $name;
		$GLOBALS['%s']->pop();
	}}
	public $field;
	public $type;
	public $name;
	public function applyInjection($target, $injector) {
		$GLOBALS['%s']->push("minject.point.PropertyInjectionPoint::applyInjection");
		$__hx__spos = $GLOBALS['%s']->length;
		$response = $injector->getValueForType($this->type, $this->name);
		if($response === null) {
			$targetName = Type::getClassName(Type::getClass($target));
			throw new HException("Injector is missing a mapping to handle injection into property \"" . _hx_string_or_null($this->field) . "\" of " . _hx_string_or_null(("object \"" . _hx_string_or_null($targetName) . "\". Target dependency: \"" . _hx_string_or_null($this->type) . "\", named \"" . _hx_string_or_null($this->name) . "\"")));
		}
		Reflect::setProperty($target, $this->field, $response);
		{
			$GLOBALS['%s']->pop();
			return $target;
		}
		$GLOBALS['%s']->pop();
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'minject.point.PropertyInjectionPoint'; }
}
