<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ da28365)
 * Haxe source file: src/microbe/comps/atoms/TextInput.hx
 */

namespace microbe\comps\atoms;

use \microbe\Microbe;
use \microbe\comps\Atom;
use \ufront\web\context\HttpContext;
use \php\Boot;
use \haxe\Log;
use \php\_Boot\HxAnon;

class TextInput extends Atom implements Microbe {
	/**
	 * @param mixed $d
	 * @param string $name
	 * @param \Array_hx $classes
	 * 
	 * @return void
	 */
	public function __construct ($d, $name = null, $classes = null) {
		#src/microbe/comps/atoms/TextInput.hx:11: lines 11-49
		parent::__construct($d, $name, $classes);
	}


	/**
	 * @param HttpContext $ctx
	 * 
	 * @return void
	 */
	public function execute ($ctx) {
		#src/microbe/comps/atoms/TextInput.hx:18: characters 3-8
		(Log::$trace)("i'ma a text Input", new HxAnon([
			"fileName" => "src/microbe/comps/atoms/TextInput.hx",
			"lineNumber" => 18,
			"className" => "microbe.comps.atoms.TextInput",
			"methodName" => "execute",
		]));
	}


	/**
	 * @return mixed
	 */
	public function getData () {
		#src/microbe/comps/atoms/TextInput.hx:46: characters 3-14
		return null;
	}


	/**
	 * @return string
	 */
	public function render () {
		#src/microbe/comps/atoms/TextInput.hx:14: characters 3-93
		return "<input " . ($this->getId()??'null') . " type=\"text\" name=\"" . ($this->data->n??'null') . "\" " . ($this->getClasses()??'null') . " value=\"" . ($this->data->v??'null') . "\">";
	}
}


Boot::registerClass(TextInput::class, 'microbe.comps.atoms.TextInput');
