<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ da28365)
 * Haxe source file: /usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx
 */

namespace haxe\io\_BytesData;

use \php\Boot;

final class BytesDataAbstract_Impl_ {


	/**
	 * @param int $length
	 * 
	 * @return Container
	 */
	static public function alloc ($length) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:40: characters 3-50
		return new Container(str_repeat(chr(0), $length));
	}


	/**
	 * @param Container $this
	 * @param int $pos
	 * @param Container $src
	 * @param int $srcpos
	 * @param int $len
	 * 
	 * @return void
	 */
	static public function blit ($this1, $pos, $src, $srcpos, $len) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:66: characters 3-122
		$this1->s = ((substr($this1->s, 0, $pos) . substr($src->s, $srcpos, $len)) . substr($this1->s, $pos + $len));
	}


	/**
	 * @param Container $this
	 * @param Container $other
	 * 
	 * @return int
	 */
	static public function compare ($this1, $other) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:54: characters 10-55
		return ($this1->s <=> $other->s);
	}


	/**
	 * @param mixed $s
	 * 
	 * @return Container
	 */
	static public function fromNativeString ($s) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:75: characters 3-26
		return new Container($s);
	}


	/**
	 * @param string $s
	 * 
	 * @return Container
	 */
	static public function fromString ($s) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:85: characters 3-26
		return new Container($s);
	}


	/**
	 * @param Container $this
	 * @param int $pos
	 * 
	 * @return int
	 */
	static public function get ($this1, $pos) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:45: characters 3-33
		return ord($this1->s[$pos]);
	}


	/**
	 * @param Container $this
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return string
	 */
	static public function getString ($this1, $pos, $len) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:58: characters 3-41
		return substr($this1->s, $pos, $len);
	}


	/**
	 * @param Container $this
	 * 
	 * @return int
	 */
	static public function get_length ($this1) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:70: characters 3-31
		return strlen($this1->s);
	}


	/**
	 * @param Container $this
	 * @param int $index
	 * @param int $val
	 * 
	 * @return void
	 */
	static public function set ($this1, $index, $val) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:50: characters 3-68
		$this1->s = substr_replace($this1->s, chr($val), $index, 1);
	}


	/**
	 * @param Container $this
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return Container
	 */
	static public function sub ($this1, $pos, $len) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:62: characters 3-50
		return new Container(substr($this1->s, $pos, $len));
	}


	/**
	 * @param Container $this
	 * 
	 * @return mixed
	 */
	static public function toNativeString ($this1) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:80: characters 3-16
		return $this1->s;
	}


	/**
	 * @param Container $this
	 * 
	 * @return string
	 */
	static public function toString ($this1) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesData.hx:90: characters 3-16
		return $this1->s;
	}
}


Boot::registerClass(BytesDataAbstract_Impl_::class, 'haxe.io._BytesData.BytesDataAbstract_Impl_');
Boot::registerGetters('haxe\\io\\_BytesData\\BytesDataAbstract_Impl_', [
	'length' => true
]);
