<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ da28365)
 * Haxe source file: /usr/local/lib/haxe/std/haxe/macro/Format.hx
 */

namespace haxe\macro;

use \php\Boot;

/**
 * The actual macro implemented for Std.format
 */
class Format {
}


Boot::registerClass(Format::class, 'haxe.macro.Format');
