<?php

// Generated by Haxe 3.4.7
class tink_core__Error_Stack_Impl_ {
	public function __construct(){}
	static function toString($this1) {
		$GLOBALS['%s']->push("tink.core._Error.Stack_Impl_::toString");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$GLOBALS['%s']->pop();
			return "Error stack not available. Compile with -D error_stack.";
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'tink.core._Error.Stack_Impl_'; }
}
