<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ da28365)
 * Haxe source file: /Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx
 */

namespace sys\ufront\web\context;

use \ufront\core\SurpriseTools;
use \tink\core\Outcome;
use \haxe\ds\StringMap;
use \php\Boot;
use \php\_Boot\HxException;
use \tink\core\TypedError;
use \tink\core\_Future\FutureObject;
use \sys\ufront\web\context\_HttpRequest\WebOverride;
use \tink\core\_Future\SyncFuture;
use \php\_NativeArray\NativeArrayIterator;
use \php\Lib;
use \php\_Boot\HxString;
use \php\Web;
use \tink\core\Noise;
use \ufront\web\context\HttpRequest as ContextHttpRequest;
use \ufront\core\_MultiValueMap\MultiValueMap_Impl_;
use \haxe\CallStack;
use \tink\core\_Lazy\LazyConst;
use \php\_Boot\HxAnon;
use \haxe\io\Error;
use \ufront\web\HttpError;

/**
 * An implementation of `ufront.web.context.HttpRequest` for Neko and PHP, based on the `neko.Web` and `php.Web` API.
 * Supported servers on Neko:
 * - `mod_neko` on Apache.
 * - `mod_tora` on Apache.
 * - `mod_tora` with FastCGI support (for Nginx etc).
 * - `nekotools server`
 * Platform quirks:
 * - Neko: `HttpRequest.parseMultipart` completely fails on `nekotools server`.
 * If you are using uploads in your app, it is recomended to have a development environment using a more thoroughly tested server.
 * - Neko and PHP: `HttpRequest.parseMultipart` callbacks **must** function synchronously, despite the fact they are supposed to return a `Future`.
 * @author Franco Ponticelli, Jason O'Neil
 */
class HttpRequest extends ContextHttpRequest {
	/**
	 * @var bool
	 */
	public $_parsed;


	/**
	 * @param string $s
	 * 
	 * @return StringMap
	 */
	static public function getMultiValueMapFromString ($s) {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:281: characters 13-32
		$this1 = new StringMap();
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:281: characters 3-33
		$map = $this1;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:282: lines 282-289
		$_g = 0;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:282: lines 282-289
		$_g1 = \Array_hx::wrap(explode("&", $s));
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:282: lines 282-289
		while ($_g < $_g1->length) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:282: characters 9-13
			$part = ($_g1->arr[$_g] ?? null);
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:282: lines 282-289
			$_g = $_g + 1;
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:283: characters 4-34
			$index = HxString::indexOf($part, "=");
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:284: lines 284-288
			if ($index > 0) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:285: characters 5-37
				$name = HxString::substr($part, 0, $index);
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:286: characters 5-36
				$val = HxString::substr($part, $index + 1);
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:287: characters 5-49
				MultiValueMap_Impl_::add($map, urldecode($name), urldecode($val));
			}
		}

		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:290: characters 3-13
		return $map;
	}


	/**
	 * @return void
	 */
	public function __construct () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:44: characters 3-18
		$this->_parsed = false;
	}


	/**
	 * @return object
	 */
	public function get_authorization () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:272: lines 272-276
		if ($this->authorization === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:273: characters 4-42
			$this->authorization = Web::getAuthorization();
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:274: lines 274-275
			if ($this->authorization === null) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:275: characters 5-45
				$this->authorization = new HxAnon([
					"user" => null,
					"pass" => null,
				]);
			}
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:277: characters 3-23
		return $this->authorization;
	}


	/**
	 * @return StringMap
	 */
	public function get_clientHeaders () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:232: lines 232-253
		if ($this->clientHeaders === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:233: characters 20-54
			$this1 = new StringMap();
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:233: characters 20-54
			$this2 = $this1;
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:233: characters 4-54
			$this->clientHeaders = $this2;
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:237: characters 5-115
			$headers = Lib::hashOfAssociativeArray(apache_request_headers());
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:241: characters 18-32
			$name = new NativeArrayIterator(array_map("strval", array_keys($headers->data)));
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:241: characters 18-32
			while ($name->hasNext()) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:241: lines 241-245
				$name1 = $name->next();
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:242: lines 242-244
				$_g = 0;
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:242: characters 19-47
				$_this = ($headers->data[$name1] ?? null);
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:242: lines 242-244
				$_g1 = \Array_hx::wrap(explode(",", $_this));
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:242: lines 242-244
				while ($_g < $_g1->length) {
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:242: characters 12-15
					$val = ($_g1->arr[$_g] ?? null);
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:242: lines 242-244
					$_g = $_g + 1;
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:243: characters 7-44
					$this3 = $this->clientHeaders;
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:243: characters 7-44
					$value = trim($val);
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:243: characters 7-44
					MultiValueMap_Impl_::add($this3, strtolower($name1), $value);

				}
			}

		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:254: characters 3-23
		return $this->clientHeaders;
	}


	/**
	 * @return string
	 */
	public function get_clientIP () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:207: lines 207-208
		if ($this->clientIP === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:208: characters 4-32
			$this->clientIP = $_SERVER["REMOTE_ADDR"];
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:209: characters 3-18
		return $this->clientIP;
	}


	/**
	 * @return StringMap
	 */
	public function get_cookies () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:194: lines 194-196
		if ($this->cookies === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:195: characters 4-55
			$this->cookies = MultiValueMap_Impl_::fromStringMap(Web::getCookies());
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:197: characters 3-17
		return $this->cookies;
	}


	/**
	 * @return string
	 */
	public function get_hostName () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:201: lines 201-202
		if ($this->hostName === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:202: characters 4-32
			$this->hostName = $_SERVER["SERVER_NAME"];
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:203: characters 3-18
		return $this->hostName;
	}


	/**
	 * @return string
	 */
	public function get_httpMethod () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:258: lines 258-261
		if ($this->httpMethod === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:259: characters 4-32
			$this->httpMethod = Web::getMethod();
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:260: characters 4-43
			if ($this->httpMethod === null) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:260: characters 28-43
				$this->httpMethod = "";
			}
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:262: characters 3-20
		return $this->httpMethod;
	}


	/**
	 * @return StringMap
	 */
	public function get_post () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:178: lines 178-189
		if ($this->post === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:179: lines 179-188
			if ($this->get_httpMethod() === "GET") {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:180: characters 12-31
				$this1 = new StringMap();
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:180: characters 5-31
				$this->post = $this1;
			} else if ($this->isMultipart()) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:183: lines 183-184
				if ($this->_parsed === false) {
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:184: characters 6-22
					$this->parseMultipart();
				}
			} else {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:187: characters 5-52
				$this->post = HttpRequest::getMultiValueMapFromString($this->get_postString());
			}
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:190: characters 3-14
		return $this->post;
	}


	/**
	 * @return string
	 */
	public function get_postString () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:62: lines 62-66
		if ($this->postString === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:63: characters 4-61
			$this->postString = ($this->get_httpMethod() === "GET" ? "" : Web::getPostData());
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:64: lines 64-65
			if ($this->postString === null) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:65: characters 5-20
				$this->postString = "";
			}
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:67: characters 3-20
		return $this->postString;
	}


	/**
	 * @return StringMap
	 */
	public function get_query () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:172: lines 172-173
		if ($this->query === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:173: characters 4-51
			$this->query = HttpRequest::getMultiValueMapFromString($this->get_queryString());
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:174: characters 3-15
		return $this->query;
	}


	/**
	 * @return string
	 */
	public function get_queryString () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:48: lines 48-57
		if ($this->queryString === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:49: characters 4-39
			$this->queryString = Web::getParamsString();
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:50: lines 50-51
			if ($this->queryString === null) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:51: characters 5-21
				$this->queryString = "";
			}
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:53: characters 4-47
			$indexOfHash = HxString::indexOf($this->queryString, "#");
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:54: lines 54-56
			if ($indexOfHash > -1) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:55: characters 5-58
				$this->queryString = HxString::substring($this->queryString, 0, $indexOfHash);
			}
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:58: characters 3-21
		return $this->queryString;
	}


	/**
	 * @return string
	 */
	public function get_scriptDirectory () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:266: lines 266-267
		if ($this->scriptDirectory === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:267: characters 4-34
			$this->scriptDirectory = (dirname($_SERVER["SCRIPT_FILENAME"])??'null') . "/";
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:268: characters 3-25
		return $this->scriptDirectory;
	}


	/**
	 * @return string
	 */
	public function get_uri () {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:213: lines 213-227
		if ($this->uri === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:214: characters 4-22
			$this->uri = Web::getURI();
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:225: characters 5-26
			$this->uri = urldecode($this->uri);
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:228: characters 3-13
		return $this->uri;
	}


	/**
	 * `HttpRequest.parseMultipart()` implementation method for mod_neko.
	 * Please see documentation on `ufront.web.context.HttpRequest.parseMultipart` for general information.
	 * Specific implementation details for neko:
	 * - This uses the `parse_multipart_data` function from the `mod_neko` NDLL, which is also used by `neko.Web.parseMultipart`.
	 * - Because of this, `onPart` and `onData` will run synchronously - the moment the callback finishes, the next callback will continue.
	 * - We suggest on neko you only use callbacks which can run synchronously.
	 * - `onEndPart` will not be called until all `onPart` and `onData` functions have finished firing.
	 * 
	 * @param \Closure $onPart
	 * @param \Closure $onData
	 * @param \Closure $onEndPart
	 * 
	 * @return FutureObject
	 */
	public function parseMultipart ($onPart = null, $onData = null, $onEndPart = null) {
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:84: lines 84-169
		$_gthis = $this;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:85: lines 85-86
		if (!$this->isMultipart()) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:86: characters 4-34
			return SurpriseTools::success();
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:89: lines 89-90
		if ($this->_parsed) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:90: characters 4-9
			throw new HxException(HttpError::internalServerError("parseMultipart() has been called more than once.", null, new HxAnon([
				"fileName" => "sys/ufront/web/context/HttpRequest.hx",
				"lineNumber" => 90,
				"className" => "sys.ufront.web.context.HttpRequest",
				"methodName" => "parseMultipart",
			])));
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:92: characters 3-17
		$this->_parsed = true;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:95: characters 3-78
		if ($onPart === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:95: characters 23-78
			$onPart = function ($_, $_1) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:95: characters 53-78
				return new SyncFuture(new LazyConst(Outcome::Success(Noise::Noise())));
			};
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:96: characters 3-80
		if ($onData === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:96: characters 23-80
			$onData = function ($_2, $_3, $_4) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:96: characters 55-80
				return new SyncFuture(new LazyConst(Outcome::Success(Noise::Noise())));
			};
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:97: characters 3-81
		if ($onEndPart === null) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:97: characters 26-81
			$onEndPart = function () {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:97: characters 56-81
				return new SyncFuture(new LazyConst(Outcome::Success(Noise::Noise())));
			};
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:99: characters 10-29
		$this1 = new StringMap();
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:99: characters 3-29
		$this->post = $this1;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:100: lines 100-106
		$noParts = true;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:100: lines 100-106
		$isFile = false;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:100: lines 100-106
		$partName = null;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:100: lines 100-106
		$fileName = null;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:100: lines 100-106
		$currentContent = null;
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:100: lines 100-106
		$callbackFutures = new \Array_hx();
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:100: lines 100-106
		$errors = new \Array_hx();
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:109: lines 109-117
		$processCallbackResult = function ($surprise)  use (&$errors, &$callbackFutures) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:110: characters 4-36
			$callbackFutures->arr[$callbackFutures->length] = $surprise;
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:110: characters 4-36
			++$callbackFutures->length;

			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:111: lines 111-116
			$surprise->handle(function ($outcome)  use (&$errors) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:112: lines 112-115
				if ($outcome->index === 1) {
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:113: characters 19-22
					$err = $outcome->params[0];
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:113: characters 25-54
					$x = $err->toString();
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:113: characters 25-54
					$errors->arr[$errors->length] = $x;
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:113: characters 25-54
					++$errors->length;

				}
			});
		};
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:118: lines 118-125
		$doEndOfPart = function ()  use (&$partName, &$processCallbackResult, &$onEndPart, &$_gthis, &$currentContent, &$isFile) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:119: lines 119-124
			if ($isFile) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:120: characters 28-39
				$doEndOfPart1 = $onEndPart();
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:120: characters 5-41
				$processCallbackResult($doEndOfPart1);
			} else if ($currentContent !== null) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:123: characters 5-41
				MultiValueMap_Impl_::add($_gthis->get_post(), $partName, $currentContent);
			}
		};
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:126: lines 126-138
		$doPart = function ($newPartName, $newPartFilename)  use (&$doEndOfPart, &$partName, &$processCallbackResult, &$noParts, &$_gthis, &$currentContent, &$isFile, &$fileName, &$onPart) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:127: characters 4-17
			$doEndOfPart();
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:128: characters 4-19
			$noParts = false;
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:129: characters 4-25
			$currentContent = null;
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:130: characters 4-38
			$partName = urldecode($newPartName);
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:131: characters 4-18
			$isFile = false;
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:132: lines 132-137
			if (($newPartFilename !== null) && ($newPartFilename !== "")) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:133: characters 5-43
				$fileName = urldecode($newPartFilename);
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:134: characters 5-33
				MultiValueMap_Impl_::add($_gthis->get_post(), $partName, $fileName);
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:135: characters 28-53
				$doPart1 = $onPart($partName, $fileName);
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:135: characters 5-55
				$processCallbackResult($doPart1);
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:136: characters 5-18
				$isFile = true;
			}
		};
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:139: lines 139-147
		$doData = function ($bytes, $pos, $len)  use (&$processCallbackResult, &$onData, &$currentContent, &$isFile) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:140: lines 140-146
			if ($isFile) {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:141: characters 5-64
				if ($len > 0) {
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:141: characters 41-62
					$doData1 = $onData($bytes, $pos, $len);
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:141: characters 18-64
					$processCallbackResult($doData1);
				}
			} else {
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:144: characters 5-52
				if ($currentContent === null) {
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:144: characters 33-52
					$currentContent = "";
				}
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:145: characters 23-47
				$currentContent1 = null;
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:145: characters 23-47
				if (($pos < 0) || ($len < 0) || (($pos + $len) > $bytes->length)) {
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:145: characters 23-47
					throw new HxException(Error::OutsideBounds());
				} else {
					#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:145: characters 23-47
					$currentContent1 = substr($bytes->b->s, $pos, $len);
				}
				#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:145: characters 5-47
				$currentContent = ($currentContent??'null') . ($currentContent1??'null');
			}
		};
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:150: lines 150-163
		try {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:154: characters 5-49
			WebOverride::parseMultipart($doPart, $doData);
		} catch (\Throwable $__hx__caught_e) {
			CallStack::saveExceptionTrace($__hx__caught_e);
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:160: characters 4-75
			$stack = CallStack::toString(CallStack::exceptionStack());
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:161: characters 4-59
			$err1 = "Failed to parse multipart data: " . (\Std::string($e)??'null') . "\x0A" . ($stack??'null');
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:162: characters 4-22
			$errors->arr[$errors->length] = $err1;
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:162: characters 4-22
			++$errors->length;

		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:166: characters 3-38
		if ($noParts === false) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:166: characters 25-38
			$doEndOfPart();
		}
		#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:167: lines 167-168
		if ($errors->length > 0) {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:167: characters 33-115
			return new SyncFuture(new LazyConst(Outcome::Failure(TypedError::withData(null, "Error parsing multipart request data", $errors, new HxAnon([
				"fileName" => "sys/ufront/web/context/HttpRequest.hx",
				"lineNumber" => 167,
				"className" => "sys.ufront.web.context.HttpRequest",
				"methodName" => "parseMultipart",
			])))));
		} else {
			#/Users/ut/Documents/LAB/ufront-mvc/src/sys/ufront/web/context/HttpRequest.hx:168: characters 15-40
			return new SyncFuture(new LazyConst(Outcome::Success(Noise::Noise())));
		}
	}
}


Boot::registerClass(HttpRequest::class, 'sys.ufront.web.context.HttpRequest');
