<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ da28365)
 * Haxe source file: /usr/local/lib/haxe/lib/tink_io/0,5,0/src/tink/io/Pipe.hx
 */

namespace tink\io;

use \php\Boot;
use \tink\core\TypedError;
use \php\_Boot\HxEnum;

class PipeResult extends HxEnum {
	/**
	 * @return PipeResult
	 */
	static public function AllWritten () {
		static $inst = null;
		if (!$inst) $inst = new PipeResult('AllWritten', 0, []);
		return $inst;
	}


	/**
	 * @return PipeResult
	 */
	static public function SinkEnded () {
		static $inst = null;
		if (!$inst) $inst = new PipeResult('SinkEnded', 2, []);
		return $inst;
	}


	/**
	 * @param TypedError $e
	 * 
	 * @return PipeResult
	 */
	static public function SinkFailed ($e) {
		return new PipeResult('SinkFailed', 1, [$e]);
	}


	/**
	 * @param TypedError $e
	 * 
	 * @return PipeResult
	 */
	static public function SourceFailed ($e) {
		return new PipeResult('SourceFailed', 3, [$e]);
	}


	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			0 => 'AllWritten',
			2 => 'SinkEnded',
			1 => 'SinkFailed',
			3 => 'SourceFailed',
		];
	}


	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'AllWritten' => 0,
			'SinkEnded' => 0,
			'SinkFailed' => 1,
			'SourceFailed' => 1,
		];
	}
}


Boot::registerClass(PipeResult::class, 'tink.io.PipeResult');
