<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ da28365)
 * Haxe source file: /usr/local/lib/haxe/lib/tink_io/0,5,0/src/tink/io/StreamParser.hx
 */

namespace tink\io;

use \tink\core\Outcome;
use \php\Boot;
use \php\_Boot\HxAnon;

/**
 * Parsers, once created, should not cause side effects outside themselves, otherwise you will get really weird bugs.
 */
interface StreamParser {
	/**
	 * @return Outcome
	 */
	public function eof () ;


	/**
	 * @return int
	 */
	public function minSize () ;


	/**
	 * @param Buffer $buffer
	 * 
	 * @return Outcome
	 */
	public function progress ($buffer) ;
}


Boot::registerClass(StreamParser::class, 'tink.io.StreamParser');
Boot::registerMeta(StreamParser::class, new HxAnon(["obj" => new HxAnon(["interface" => null])]));
