<?php

// Generated by Haxe 3.4.7
class app_Apis extends ufront_api_UFApiContext {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		$GLOBALS['%s']->push("app.Apis::new");
		$__hx__spos = $GLOBALS['%s']->length;
		parent::__construct();
		$GLOBALS['%s']->pop();
	}}
	public $imagebase;
	public $microbe;
	public $upapi;
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	function __toString() { return 'app.Apis'; }
}
app_Apis::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("rtti" => (new _hx_array(array((new _hx_array(array("imagebase", "microbe.apis.ImageBaseApi", ""))), (new _hx_array(array("microbe", "microbe.apis.MicrobialApi", ""))), (new _hx_array(array("upapi", "microbe.apis.UpApi", "")))))), "apiList" => (new _hx_array(array("microbe.apis.ImageBaseApi", "microbe.apis.MicrobialApi", "microbe.apis.UpApi")))))));
