<?php

// Generated by Haxe 3.4.7
class tink_core_NamedWith {
	public function __construct($name, $value) {
		if(!php_Boot::$skip_constructor) {
		$GLOBALS['%s']->push("tink.core.NamedWith::new");
		$__hx__spos = $GLOBALS['%s']->length;
		$this->name = $name;
		$this->value = $value;
		$GLOBALS['%s']->pop();
	}}
	public $name;
	public $value;
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'tink.core.NamedWith'; }
}
