<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ da28365)
 * Haxe source file: /usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx
 */

namespace haxe\io;

use \haxe\_Int64\___Int64;
use \php\Boot;
use \php\_Boot\HxException;
use \haxe\io\_BytesData\Container;

class BytesBuffer {
	/**
	 * @var string
	 */
	public $b;


	/**
	 * @return void
	 */
	public function __construct () {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:33: characters 3-9
		$this->b = "";
	}


	/**
	 * @param Bytes $src
	 * 
	 * @return void
	 */
	public function add ($src) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:41: characters 3-55
		$this->b = ($this->b . $src->b->s);
	}


	/**
	 * @param int $byte
	 * 
	 * @return void
	 */
	public function addByte ($byte) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:37: characters 3-41
		$this->b = ($this->b . chr($byte));
	}


	/**
	 * @param Bytes $src
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return void
	 */
	public function addBytes ($src, $pos, $len) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:69: lines 69-73
		if (($pos < 0) || ($len < 0) || (($pos + $len) > $src->length)) {
			#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:70: characters 4-9
			throw new HxException(Error::OutsideBounds());
		} else {
			#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:72: characters 8-64
			$left = $this->b;
			#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:72: characters 25-52
			$this_s = substr($src->b->s, $pos, $len);
			#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:72: characters 4-5
			$this->b = ($left . $this_s);
		}
	}


	/**
	 * @param float $v
	 * 
	 * @return void
	 */
	public function addDouble ($v) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:65: characters 3-36
		$this->addInt64(FPHelper::doubleToI64($v));
	}


	/**
	 * @param float $v
	 * 
	 * @return void
	 */
	public function addFloat ($v) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:61: characters 3-35
		$this->addInt32(unpack("l", pack("f", $v))[1]);
	}


	/**
	 * @param int $v
	 * 
	 * @return void
	 */
	public function addInt32 ($v) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:49: characters 3-18
		$this->b = ($this->b . chr($v & 255));
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:50: characters 3-23
		$this->b = ($this->b . chr(($v >> 8) & 255));
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:51: characters 3-24
		$this->b = ($this->b . chr(($v >> 16) & 255));
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:52: characters 3-18
		$this->b = ($this->b . chr(Boot::shiftRightUnsigned($v, 24)));
	}


	/**
	 * @param ___Int64 $v
	 * 
	 * @return void
	 */
	public function addInt64 ($v) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:56: characters 3-18
		$this->addInt32($v->low);
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:57: characters 3-19
		$this->addInt32($v->high);
	}


	/**
	 * @param string $v
	 * 
	 * @return void
	 */
	public function addString ($v) {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:45: characters 3-26
		$this->b = ($this->b . $v);
	}


	/**
	 * Returns either a copy or a reference of the current bytes.
	 * Once called, the buffer can no longer be used.
	 * 
	 * @return Bytes
	 */
	public function getBytes () {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:81: characters 25-33
		$bytes = strlen($this->b);
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:81: characters 3-38
		$bytes1 = new Bytes($bytes, new Container($this->b));
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:82: characters 3-11
		$this->b = null;
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:83: characters 3-15
		return $bytes1;
	}


	/**
	 * @return int
	 */
	public function get_length () {
		#/usr/local/lib/haxe/std/php/_std/haxe/io/BytesBuffer.hx:87: characters 3-18
		return strlen($this->b);
	}
}


Boot::registerClass(BytesBuffer::class, 'haxe.io.BytesBuffer');
Boot::registerGetters('haxe\\io\\BytesBuffer', [
	'length' => true
]);
