<?php

// Generated by Haxe 3.4.7
class thx__Ord_Ordering_Impl_ {
	public function __construct(){}
	static function fromInt($value) {
		$GLOBALS['%s']->push("thx._Ord.Ordering_Impl_::fromInt");
		$__hx__spos = $GLOBALS['%s']->length;
		if($value < 0) {
			$tmp = thx_OrderingImpl::$LT;
			$GLOBALS['%s']->pop();
			return $tmp;
		} else {
			if($value > 0) {
				$tmp = thx_OrderingImpl::$GT;
				$GLOBALS['%s']->pop();
				return $tmp;
			} else {
				$tmp = thx_OrderingImpl::$EQ;
				$GLOBALS['%s']->pop();
				return $tmp;
			}
		}
		$GLOBALS['%s']->pop();
	}
	static function fromFloat($value) {
		$GLOBALS['%s']->push("thx._Ord.Ordering_Impl_::fromFloat");
		$__hx__spos = $GLOBALS['%s']->length;
		if($value < 0) {
			$tmp = thx_OrderingImpl::$LT;
			$GLOBALS['%s']->pop();
			return $tmp;
		} else {
			if($value > 0) {
				$tmp = thx_OrderingImpl::$GT;
				$GLOBALS['%s']->pop();
				return $tmp;
			} else {
				$tmp = thx_OrderingImpl::$EQ;
				$GLOBALS['%s']->pop();
				return $tmp;
			}
		}
		$GLOBALS['%s']->pop();
	}
	static function toInt($this1) {
		$GLOBALS['%s']->push("thx._Ord.Ordering_Impl_::toInt");
		$__hx__spos = $GLOBALS['%s']->length;
		switch($this1->index) {
		case 0:{
			$GLOBALS['%s']->pop();
			return -1;
		}break;
		case 1:{
			$GLOBALS['%s']->pop();
			return 1;
		}break;
		case 2:{
			$GLOBALS['%s']->pop();
			return 0;
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'thx._Ord.Ordering_Impl_'; }
}
