<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ da28365)
 * Haxe source file: /usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx
 */

namespace haxe\ds;

use \php\Boot;

/**
 * A tree node of `haxe.ds.BalancedTree`.
 */
class TreeNode {
	/**
	 * @var int
	 */
	public $_height;
	/**
	 * @var mixed
	 */
	public $key;
	/**
	 * @var TreeNode
	 */
	public $left;
	/**
	 * @var TreeNode
	 */
	public $right;
	/**
	 * @var mixed
	 */
	public $value;


	/**
	 * @param TreeNode $l
	 * @param mixed $k
	 * @param mixed $v
	 * @param TreeNode $r
	 * @param int $h
	 * 
	 * @return void
	 */
	public function __construct ($l, $k, $v, $r, $h = -1) {
		#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:229: lines 229-238
		if ($h === null) {
			#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:229: lines 229-238
			$h = -1;
		}
		#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:230: characters 3-11
		$this->left = $l;
		#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:231: characters 3-10
		$this->key = $k;
		#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:232: characters 3-12
		$this->value = $v;
		#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:233: characters 3-12
		$this->right = $r;
		#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:234: lines 234-237
		if ($h === -1) {
			#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:235: characters 14-95
			$tmp = null;
			#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:235: characters 15-32
			$_this = $this->left;
			#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:235: characters 35-53
			$_this1 = $this->right;
			#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:235: characters 14-95
			if ((($_this === null ? 0 : $_this->_height)) > (($_this1 === null ? 0 : $_this1->_height))) {
				#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:235: characters 56-73
				$_this2 = $this->left;
				#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:235: characters 14-95
				$tmp = ($_this2 === null ? 0 : $_this2->_height);
			} else {
				#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:235: characters 76-94
				$_this3 = $this->right;
				#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:235: characters 14-95
				$tmp = ($_this3 === null ? 0 : $_this3->_height);
			}
			#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:235: characters 4-99
			$this->_height = $tmp + 1;
		} else {
			#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:237: characters 4-15
			$this->_height = $h;
		}
	}


	/**
	 * @return string
	 */
	public function toString () {
		#/usr/local/lib/haxe/std/haxe/ds/BalancedTree.hx:243: characters 3-118
		return ((($this->left === null ? "" : ($this->left->toString()??'null') . ", "))??'null') . (("" . (\Std::string($this->key)??'null') . "=" . (\Std::string($this->value)??'null'))??'null') . ((($this->right === null ? "" : ", " . ($this->right->toString()??'null')))??'null');
	}


	public function __toString() {
		return $this->toString();
	}
}


Boot::registerClass(TreeNode::class, 'haxe.ds.TreeNode');
