<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ da28365)
 * Haxe source file: /usr/local/lib/haxe/std/haxe/ds/WeakMap.hx
 */

namespace haxe\ds;

use \haxe\IMap;
use \php\Boot;
use \php\_Boot\HxException;

/**
 * WeakMap allows mapping of object keys to arbitrary values.
 * The keys are considered to be weak references on static targets.
 * See `Map` for documentation details.
 * @see https://haxe.org/manual/std-Map.html
 */
class WeakMap implements IMap {
	/**
	 * Creates a new WeakMap.
	 * 
	 * @return void
	 */
	public function __construct () {
		#/usr/local/lib/haxe/std/haxe/ds/WeakMap.hx:40: characters 3-8
		throw new HxException("Not implemented for this platform");
	}


	/**
	 * See `Map.copy`
	 * 
	 * @return WeakMap
	 */
	public function copy () {
		#/usr/local/lib/haxe/std/haxe/ds/WeakMap.hx:88: characters 3-14
		return null;
	}


	/**
	 * See `Map.exists`
	 * 
	 * @param mixed $key
	 * 
	 * @return bool
	 */
	public function exists ($key) {
		#/usr/local/lib/haxe/std/haxe/ds/WeakMap.hx:60: characters 3-15
		return false;
	}


	/**
	 * See `Map.get`
	 * 
	 * @param mixed $key
	 * 
	 * @return mixed
	 */
	public function get ($key) {
		#/usr/local/lib/haxe/std/haxe/ds/WeakMap.hx:53: characters 3-14
		return null;
	}


	/**
	 * See `Map.iterator`
	 * 
	 * @return object
	 */
	public function iterator () {
		#/usr/local/lib/haxe/std/haxe/ds/WeakMap.hx:81: characters 3-14
		return null;
	}


	/**
	 * See `Map.keys`
	 * 
	 * @return object
	 */
	public function keys () {
		#/usr/local/lib/haxe/std/haxe/ds/WeakMap.hx:74: characters 3-14
		return null;
	}


	/**
	 * See `Map.remove`
	 * 
	 * @param mixed $key
	 * 
	 * @return bool
	 */
	public function remove ($key) {
		#/usr/local/lib/haxe/std/haxe/ds/WeakMap.hx:67: characters 3-15
		return false;
	}


	/**
	 * See `Map.set`
	 * 
	 * @param mixed $key
	 * @param mixed $value
	 * 
	 * @return void
	 */
	public function set ($key, $value) {
	}


	/**
	 * See `Map.toString`
	 * 
	 * @return string
	 */
	public function toString () {
		#/usr/local/lib/haxe/std/haxe/ds/WeakMap.hx:95: characters 3-14
		return null;
	}


	public function __toString() {
		return $this->toString();
	}
}


Boot::registerClass(WeakMap::class, 'haxe.ds.WeakMap');
